import { createAllowedComputer } from "./testing/authorized-fixtures.js";
import "./testing/frontend-artifact.js";
/** Docker-only browser worker acceptance. CDP injects push events; this does not
 * claim FCM reception. No PushManager or Notification implementation is faked. */
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { createECDH, randomBytes } from "node:crypto";
import webpush from "web-push";
import { Store } from "../src/persistence/store.js";
import { createHub, reserveAgent, passwordHash, secret } from "../src/domain/commands.js";
import { independentAuthority } from "../src/hub/independent.js";
import { createHubApp } from "../src/hub/app.js";
import { NotificationInbox, subscriptionTag } from "../src/hub/notifications.js";
import { WebPushProvider } from "../src/hub/web-push.js";
import { HubSessions } from "../src/hub/sessions.js";
import { Tunnels } from "../src/protocol/tunnels.js";
import { NativeRuntime } from "../src/computer/native/runtime.js";
import { createComputerApi } from "../src/computer/api.js";
assert.ok(existsSync("/.dockerenv"), "Run in Docker");
const home = await mkdtemp(join(tmpdir(), "browser-push-")), workspace = join(home,"workspace"), origin = "http://127.0.0.1:19944", clientOrigin = "http://127.0.0.1:19945";
await mkdir(workspace,{recursive:true}); await mkdir(join(home,".pi","agent"),{recursive:true});
await writeFile(join(home,".pi","agent","models.json"),JSON.stringify({providers:{fixture:{baseUrl:"http://127.0.0.1:19946/v1",api:"openai-completions",apiKey:"fixture-only",models:[{id:"fixture",name:"Controlled fixture",reasoning:false,input:["text"],contextWindow:32000,maxTokens:2048,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}}]}}}));
await writeFile(join(home,".pi","agent","settings.json"),JSON.stringify({defaultProvider:"fixture",defaultModel:"fixture",defaultThinkingLevel:"off",defaultProjectTrust:"always",quietStartup:true}));
Object.assign(process.env,{PI_BIN:"/opt/codoxear-tools/node/bin/pi",CODEX_BIN:"/opt/codoxear-tools/node/bin/codex",IS_SANDBOX:"1"});
const store = new Store(":memory:"); store.change(s=>s.users.push({id:"alice",email:"alice@push.invalid",name:"Alice",passwordHash:passwordHash("isolated-password"),disabled:false}));
const computer=store.change(s=>createAllowedComputer(s,"alice",createHub(s,"alice","Push test").id,"Real Pi","alice"));
const local=await independentAuthority({origin,hubId:computer.computer.hubId,store,otpKey:secret(),secureCookies:false});
const session=local.authority.accounts.password("alice@push.invalid","isolated-password","fixture").session;
const vapid=webpush.generateVAPIDKeys(), provider=new WebPushProvider({...vapid,subject:"mailto:push@fixture.invalid"});
const inbox=new NotificationInbox(join(home,"push.sqlite"),computer.computer.hubId,async(sid,aid,cid,binding)=>{local.authority.authorizeNotification(computer.computer.hubId,sid,aid,cid,binding);},provider);
const sessions=new HubSessions(join(home,"hub.sqlite")), tunnels=new Tunnels();
const hub=await createHubApp({origin,localIdentity:local.identity,clientOrigins:[clientOrigin],authority:local.client,notifications:inbox,sessions,tunnels,secureCookies:false});
const sockets = new Set<import("node:net").Socket>(); hub.server.on("connection",socket=>{sockets.add(socket);socket.once("close",()=>sockets.delete(socket));});
await hub.listen({host:"127.0.0.1",port:19944});
const native=new NativeRuntime(home,workspace,join(home,"computer")), api=createComputerApi(join(home,"computer"));
await api.attach({version:1,hubUrl:origin,hubId:computer.computer.hubId,computerId:computer.computer.id,credential:computer.credential,runtime:"native",nativeHome:home,workspacePath:workspace});
const service=api.service(), staticClient=spawn(process.execPath,["frontend/serve.mjs"],{env:{...process.env,CODOXEAR_CLIENT_PORT:"19945"},stdio:"ignore"});
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE!), browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:["--no-sandbox","--disable-dev-shm-usage"]});
const context=await browser.newContext({viewport:{width:1440,height:1000}}); await context.grantPermissions(["notifications"],{origin:clientOrigin});
const page=await context.newPage(), cdp=await context.newCDPSession(page), checks:string[]=[], errors:string[]=[];
page.on("pageerror",(e:Error)=>errors.push(e.message)); page.setDefaultTimeout(20000);
const registrations=new Map<string,any>(); cdp.on("ServiceWorker.workerRegistrationUpdated",(e:any)=>{for(const r of e.registrations)registrations.set(r.scopeURL,r);}); await cdp.send("ServiceWorker.enable");
async function until(check:()=>Promise<boolean>|boolean,ms=30000){const deadline=Date.now()+ms;while(!await check()){if(Date.now()>deadline)throw Error("Timeout");await new Promise(r=>setTimeout(r,100));}}
const pass=(label:string)=>{checks.push(label);console.log("PASS",label);}; let localId:string|undefined, realPushResult="not attempted";
try {
  await mkdir("artifacts",{recursive:true}); await until(async()=>{try{return(await fetch(clientOrigin+"/health")).ok;}catch{return false;}});
  await service.start(); await until(()=>tunnels.online(computer.computer.id));
  const created=await native.execute({op:"create",agentId:"push-fixture",backend:"pi",name:"Native push process"}) as {localId:string};localId=created.localId;
  await until(async()=>(await native.request(`/api/sessions/${created.localId}/state`)).readiness==="ready",60000);
  const agent=store.change(s=>{const a=reserveAgent(s,"alice",computer.computer.id,"Native push process","pi");a.localId=created.localId;a.state="ready";return a;});
  const accessToken=await local.authority.tokens.issue(session,origin,"identity_access"), login={id:"push-login",accountKey:"push-account",origin,hubId:computer.computer.hubId,name:"Push test",accountId:"alice",accessToken,refreshToken:"fixture-unused-refresh-token",expiresAt:Date.now()+3600000,identity:{name:"Alice",method:"password",key:"alice"}};
  await page.goto(clientOrigin+"/health"); await page.evaluate(async(login:any)=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("codoxear-client-identities",1);r.onupgradeneeded=()=>r.result.createObjectStore("credentials");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const t=db.transaction("credentials","readwrite");t.objectStore("credentials").put(login,login.id);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});},login);
  await page.goto(clientOrigin+"/#session="+encodeURIComponent(login.accountKey+"~"+agent.id));
  await page.locator("#settingsBtnSide").waitFor(); await page.locator("#settingsBtnSide").click(); await page.locator("#settingsViewer").waitFor({state:"visible"});
  await page.locator("#notificationSettingsToggleBtn").waitFor(); await until(async()=>(await page.locator("#notificationSettingsStatus").textContent()).includes("Background notifications are off"));
  pass("Real static client settings shows account-scoped background notifications with configured public VAPID key");
  const scoped="/api/notifications/subscription?__agent="+encodeURIComponent(login.accountKey+"~"+agent.id);
  const initial=await page.evaluate(async(url:string)=>{const r=await fetch(url);return{status:r.status,value:await r.json()};},scoped);assert.equal(initial.status,200);assert.equal(initial.value.vapid_public_key,vapid.publicKey);assert.ok(!JSON.stringify(initial.value).includes(vapid.privateKey));
  const receiver=createECDH("prime256v1");receiver.generateKeys();const subscription={endpoint:"https://fcm.googleapis.com/wp/controlled-fixture",expirationTime:null,keys:{p256dh:receiver.getPublicKey().toString("base64url"),auth:randomBytes(16).toString("base64url")}};
  const registered=await page.evaluate(async({url,subscription}:any)=>{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription})});return{status:r.status,value:await r.json()};},{url:scoped,subscription});assert.equal(registered.status,200);
  const scope=registered.value.push_scope;
  await page.evaluate(async({script,scope}:any)=>{const registration=await navigator.serviceWorker.register(script,{scope});if(!registration.active)await new Promise<void>((resolve,reject)=>{const worker=registration.installing||registration.waiting;if(!worker)return reject(Error("worker missing"));worker.addEventListener("statechange",()=>{if(worker.state==="activated")resolve();if(worker.state==="redundant")reject(Error("redundant"));});});},{script:registered.value.push_worker,scope});
  await until(()=>!!registrations.get(scope));
  const hint={version:1,id:"a".repeat(64),localId:created.localId,kind:"completion",occurredAt:Date.now(),hubId:computer.computer.hubId,userId:"alice",clientId:login.id,installationId:registered.value.installation_id,computerId:computer.computer.id,agentId:agent.id,binding:computer.computer.binding,subscriptionTag:subscriptionTag(JSON.stringify(subscription))};
  const notifications=()=>page.evaluate(async(scope:string)=>{const r=await navigator.serviceWorker.getRegistration(scope);return r ? (await r.getNotifications()).map(n=>({title:n.title,body:n.body,tag:n.tag,data:n.data})) : [];},scope);
  const inject=async(value:unknown)=>cdp.send("ServiceWorker.deliverPushMessage",{origin:clientOrigin,registrationId:registrations.get(scope).registrationId,data:JSON.stringify(value)});
  await inject(hint);await until(async()=>(await notifications()).length===1);assert.equal((await notifications())[0].title,"Agent finished");
  pass("Chrome dispatches a genuine service-worker push event, reauthorizes through the real independent Hub, and stores a generic notification");
  const target=context.serviceWorkers().find((w:any)=>w.url().includes("push=push-login"));assert.ok(target);
  await page.evaluate(()=>history.replaceState(null,"","/#push-click-proof=1"));
  await target.evaluate(async()=>{const notification=(await (self as unknown as ServiceWorkerGlobalScope).registration.getNotifications())[0]!;(self as unknown as ServiceWorkerGlobalScope).dispatchEvent(new NotificationEvent("notificationclick",{notification}));});
  await until(async()=>new URLSearchParams(new URL(page.url()).hash.slice(1)).get("session")===login.accountKey+"~"+agent.id);await until(async()=>(await notifications()).length===0);
  pass("Controlled notificationclick event executes the worker handler and routes to the same-origin account-scoped agent");
  const replacement={...subscription,endpoint:"https://fcm.googleapis.com/wp/replacement-fixture"};
  assert.equal(await page.evaluate(async({url,subscription}:any)=>(await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription})})).status,{url:scoped,subscription:replacement}),200);
  await inject({...hint,id:"b".repeat(64)});await new Promise(r=>setTimeout(r,700));assert.equal((await notifications()).length,0);pass("Queued push from the previous subscription is rejected after endpoint rotation");
  const current={...hint,id:"c".repeat(64),subscriptionTag:subscriptionTag(JSON.stringify(replacement))};await inject(current);await until(async()=>(await notifications()).length===1);
  store.change(s=>{s.computers.find(c=>c.id===computer.computer.id)!.binding++;});
  await page.evaluate(()=>history.replaceState(null,"","/#push-revoked-click=1"));
  await target.evaluate(async()=>{const notification=(await (self as unknown as ServiceWorkerGlobalScope).registration.getNotifications())[0]!;(self as unknown as ServiceWorkerGlobalScope).dispatchEvent(new NotificationEvent("notificationclick",{notification}));});
  await inject({...current,id:"d".repeat(64)});await new Promise(r=>setTimeout(r,700));assert.equal((await notifications()).length,0);assert.ok(page.url().endsWith("#push-revoked-click=1"));pass("Changed computer binding blocks stale push and stale notificationclick authorization");
  store.change(s=>{s.computers.find(c=>c.id===computer.computer.id)!.binding=computer.computer.binding;});
  const browserContextId=(await cdp.send("Target.getTargetInfo")).targetInfo.browserContextId;
  await cdp.send("Browser.setPermission",{permission:{name:"notifications"},setting:"denied",origin:clientOrigin,browserContextId});
  assert.equal(await page.evaluate(()=>Notification.permission),"denied");
  await inject({...current,id:"f".repeat(64)});await new Promise(r=>setTimeout(r,700));assert.equal((await notifications()).length,0);pass("Real browser notification permission denial blocks display");
  await cdp.send("Browser.setPermission",{permission:{name:"notifications"},setting:"granted",origin:clientOrigin,browserContextId});
  store.change(s=>{s.users.find(u=>u.id==="alice")!.disabled=true;});
  await inject({...current,id:"1".repeat(64)});await new Promise(r=>setTimeout(r,700));assert.equal((await notifications()).length,0);pass("Current account revocation blocks background notification authorization");
  store.change(s=>{s.users.find(u=>u.id==="alice")!.disabled=false;});
  await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("codoxear-client-identities",1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const t=db.transaction("credentials","readwrite"),s=t.objectStore("credentials"),r=s.get("push-login");r.onsuccess=()=>s.put({...r.result,pushSession:"replacement-login-session"},"push-login");t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});});
  await inject({...current,id:"2".repeat(64)});await new Promise(r=>setTimeout(r,700));assert.equal((await notifications()).length,0);
  const relogin=await page.evaluate(async(url:string)=>{const r=await fetch(url);return{status:r.status,value:await r.json()};},scoped);assert.equal(relogin.status,200);assert.notEqual(relogin.value.installation_id,hint.installationId);assert.equal(inbox.counts().subscriptions,0);
  pass("Replacing the saved Hub login fences old push and rotates the account's installation lease");
  assert.equal(await page.evaluate(async({url,subscription}:any)=>(await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription})})).status,{url:scoped,subscription:replacement}),200);
  const disconnected=await page.evaluate(async()=>(await fetch("/api/client/push/disconnect/push-login",{method:"POST"})).status);assert.equal(disconnected,200);assert.equal(inbox.counts().subscriptions,0);
  await inject({...current,id:"e".repeat(64)}).catch(()=>{});await new Promise(r=>setTimeout(r,500));assert.equal((await notifications()).length,0);pass("Disconnect removes the saved account and Hub subscription; later push cannot notify or restore access");
  // Real PushManager is attempted independently; a controlled endpoint was used
  // above only to test event authorization, never presented as an FCM subscription.
  realPushResult=await page.evaluate(async(publicKey:string)=>{const registration=await navigator.serviceWorker.register("/client-worker.js?push=provider-probe",{scope:"/push/provider-probe/"});await new Promise<void>(resolve=>{if(registration.active)return resolve();const worker=registration.installing||registration.waiting;worker?.addEventListener("statechange",()=>{if(worker.state==="activated")resolve();});});const bytes=Uint8Array.from(atob(publicKey.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));const permission=Notification.permission,pushPermission=await registration.pushManager.permissionState({userVisibleOnly:true,applicationServerKey:bytes});const result=await Promise.race([registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes}).then(subscription=>"subscribed:"+new URL(subscription.endpoint).origin,error=>String(error)),new Promise<string>(resolve=>setTimeout(()=>resolve("timeout: isolated Docker has no provider egress"),10000))]);return JSON.stringify({notificationPermission:permission,pushPermission,result});},vapid.publicKey);
  console.log("REAL_PUSH_MANAGER",realPushResult);
  await page.screenshot({path:"artifacts/web-push-settings.png"});
  await writeFile("artifacts/web-push-results.json",JSON.stringify({browserVersion:browser.version(),checks,errors,realPushManager:realPushResult,realProviderDelivery:false,limitations:["Push events injected via Chrome DevTools; notificationclick dispatched in real worker. OS notification click and FCM delivery are not claimed.","Real-device/iOS/Harmony acceptance requires configured provider/device."]},null,2));
  assert.deepEqual(errors,[]);
} catch(error) {await page.screenshot({path:"artifacts/web-push-failure.png"}).catch(()=>{});throw error;}
finally {await browser.close();if(localId)await native.request(`/api/sessions/${localId}/delete`,"POST").catch(()=>{});await service.stop();const stopped=new Promise<void>(resolve=>staticClient.once("exit",()=>resolve()));staticClient.kill("SIGTERM");await stopped;for(const socket of sockets)socket.destroy();hub.server.closeAllConnections();await hub.close();local.identity.server.closeAllConnections();await local.identity.close();inbox.close();sessions.close();store.close();native.close();}
