"""Generate native palette constants from the checked-in web themes."""
from pathlib import Path
import re, json
root = Path(__file__).resolve().parents[3]
def tokens(s):
    return dict(re.findall(r'--([\w-]+):\s*([^;]+);', re.sub(r'/\*.*?\*/', '', s, flags=re.S)))
base = tokens(re.search(r':root\s*\{([^}]+)', (root/'codoxear/static/app.css').read_text())[1])
fields = {'ink':'ink','paper':'paper','background':'bg','wash':'wash','hairline':'hairline','panel':'panel','border':'border','text':'text','muted':'muted','accent':'accent','primary':'accent-strong','onPrimary':'on-accent','danger':'danger','userBubble':'bubble-user','assistantBubble':'bubble-assistant','activeSession':'session-active','code':'surface-code','subtle':'surface-subtle'}
rows = []
variable_rows = []
for family in ['clay','paper','slate']:
    content = (root/f'codoxear/static/themes/{family}.css').read_text()
    for mode in ['light','dark']:
        values = dict(base)
        for selector, body in re.findall(r'([^{}]+)\{([^{}]*)\}', content):
            sel = re.sub(r'/\*.*?\*/','',selector,flags=re.S).strip()
            if sel == f':root[data-theme="{family}"]' or (mode=='dark' and sel == f':root[data-theme="{family}"][data-mode="dark"]'):
                values.update(tokens(body))
        values.setdefault('accent',values['ink'])
        values.setdefault('accent-strong',values['ink'])
        values.setdefault('on-accent',values['paper'])
        variable_rows.append(f"    case '{family}-{mode}': return " + json.dumps(values) + ';')
        def resolve(v):
            for _ in range(8):
                v = re.sub(r'var\(--([\w-]+)\)',lambda m: values.get(m[1],'#000000'),v)
            return v
        # SVG image color filters differ between stroke and fill on ArkUI.
        # Bake the same web monochrome treatment into theme-specific vectors.
        icon_dir = root/f'frontend/harmonyos/entry/src/main/resources/rawfile/logos/{family}-{mode}'
        icon_dir.mkdir(parents=True, exist_ok=True)
        for backend in ['codex', 'pi', 'cc']:
            svg = (root/f'codoxear/static/logos/{backend}.svg').read_text()
            svg = re.sub(r'<defs>.*?</defs>', '', svg, flags=re.S)
            svg = re.sub(r'(fill|stroke)="(?!none")[^"]+"', lambda m: f'{m[1]}="{"#ffffff" if "invert(1)" in values["icon-muted-filter"] else "#000000"}"', svg)
            opacity = re.search(r'opacity\(([^)]+)\)', values['icon-muted-filter'])
            svg = svg.replace('<svg ', f'<svg opacity="{opacity[1] if opacity else 1}" ', 1)
            (icon_dir/f'{backend}.svg').write_text(svg)
        shell = (root/'codoxear/static/app_shell.js').read_text()
        brand = re.search(r'<svg class="sidebarLogo brandLogo".*?</svg>', shell)[0]
        brand = brand.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ')
        brand = brand.replace('class="brandLogoPage"', f'fill="{resolve(values["brand-logo-page"])}" stroke="{resolve(values["brand-logo-outline"])}"')
        brand = brand.replace('class="brandLogoFold"', f'fill="{resolve(values["brand-logo-fold"])}" stroke="{resolve(values["brand-logo-outline"])}"')
        brand = brand.replace('class="brandLogoTerminal"', f'stroke="{resolve(values["brand-logo-terminal"])}"')
        (icon_dir/'brand.svg').write_text(brand)
        props = [f"{k}: '{resolve(values[v])}'" for k,v in fields.items()]
        props += [f'radius: {0 if family=="paper" else (8 if family=="slate" else 6)}', f'cardRadius: {0 if family=="paper" else 12}',f'bubbleRadius: {0 if family=="paper" else 18}', f"family: '{family}'", f"mode: '{mode}'"]
        rows.append(f"    case '{family}-{mode}': return {{ " + ', '.join(props) + ' };')
f=root/'frontend/harmonyos/entry/src/main/ets/model/Theme.ets'
f.parent.mkdir(parents=True,exist_ok=True)
f.write_text('// Generated by scripts/sync_theme.py from the web theme tokens.\nexport interface Palette {\n'+''.join('  '+k+': string;\n' for k in fields)+'  radius: number;\n  cardRadius: number;\n  bubbleRadius: number;\n  family: string;\n  mode: string;\n}\n\nexport function palette(family: string, dark: boolean): Palette {\n  switch (family + (dark ? "-dark" : "-light")) {\n'+'\n'.join(rows)+'\n    default: return palette("clay", dark);\n  }\n}\n')

with f.open('a') as output:
    output.write('\nexport function themeVariables(family: string, dark: boolean): Record<string, string> {\n  switch (family + (dark ? "-dark" : "-light")) {\n' + '\n'.join(variable_rows) + '\n    default: return themeVariables("clay", dark);\n  }\n}\n')
