"""Wrap the repository's pinned Marked parser for the ArkTS JS boundary."""
from pathlib import Path
root = Path(__file__).resolve().parents[3]
source = (root / "codoxear/static/vendor/marked.min.js").read_text()
target = root / "frontend/harmonyos/entry/src/main/ets/vendor/marked.js"
target.write_text("// Generated by scripts/sync_marked.py; see marked.LICENSE.\nconst parser = (() => { const module = {exports: {}}; const exports = module.exports;\n" + source + "\nreturn module.exports; })();\nexport default parser;\n")
